# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        day: [day1, day2]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Lint
      working-directory: ${{matrix.day}}
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54

    - name: Build
      working-directory: ${{matrix.day}}
      run: go build -v ./...

    - name: Test
      working-directory: ${{matrix.day}}
      run: go test -v ./...
